#!/bin/bash
echo "Starting IO Benchmarks"
for i in {1..5}
do
        # Perform write test
        echo "Performing write test $i" 
	# Write one file from /dev/zero to /root/testfile by chunks of 5M bytes and 1k times
        dd if=/dev/zero of=/root/testfile bs=5M count=1k conv=fdatasync
        # Clear cache and perform read test
        echo "Performing read test $i"
        echo 3 > /proc/sys/vm/drop_caches
	# Read one file from /root/testfile by chunks of 5M bytes and 1k times
        dd if=/root/testfile of=/dev/zero bs=5M count=1k
done
rm -r -f /root/testfile
echo "IO Benchmarks Done"





