#!/bin/bash
echo "Starting IOPS Benchmarks"
apt install bonnie++
for i in {1..5}
do
        echo "Performing IOPS test $i"
	# Perform sequential and random file creation, read and delete operations on 100 * 1024 files of size varying between 500 and 1k bytes
        bonnie++ -u root -d /tmp -s 0 -n 100:1k:500
done
echo "IOPS Benchmarks Done"


